version: '3.5'

services:

  avia-front:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - '80:80'

  avia-back:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
